---
- hosts: localhost
  become: true
  gather_facts: false
  tasks:

  - name: Install Java
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items: 
      - "default-jdk"
      - "default-jre"

  - name: Download, tag and push jenkins image to local registry
    docker_image:
      name: jenkins/jenkins:lts-jdk11
      repository: docker.registry.com:5000/jenkins:v1
      source: pull
      push: yes

  - name: Create a jenkins-system namespace # so we can create secret in it
    become: false
    kubernetes.core.k8s:
      api_version: v1
      name: jenkins-system  
      kind: Namespace
      state: present

# Create docker secret with login credentials
  - name: Create docker secret
    become: false
    ansible.builtin.shell: |
      kubectl create secret docker-registry regsecret \
      --docker-server=docker.registry.com:5000 \
      --docker-username=user \
      --docker-password=password \
      --namespace=jenkins-system
    register: secret
    changed_when: secret.stdout == "secret/regsecret created"
    args:
      executable: /bin/bash

  - name: Un-Taint master node
    become: false
    shell: |
      kubectl taint nodes master-1 node-role.kubernetes.io/control-plane:NoSchedule- && \
      kubectl taint nodes master-1 node-role.kubernetes.io/master:NoSchedule-

# Setup PV for Jenkins
  - name: Setup PersistentVolume for jenkins
    become: false
    kubernetes.core.k8s:
      definition:
        kind: PersistentVolume
        apiVersion: v1
        metadata:
          name: pv-for-jenkins
        spec:
          accessModes: [ "ReadWriteOnce" ]
          capacity:
            storage: 10Gi
          hostPath:
            path: /jenkins-data
          nodeSelector:
            kubernetes.io/hostname: master-1

  - name: change permissions
    shell: sudo mkdir /jenkins-data && sudo chmod a+rw /jenkins-data 

# Add helm chart repository
  - name: Add helm chart repository for jenkins
    become: false
    kubernetes.core.helm_repository:
      name: jenkins
      repo_url: https://charts.jenkins.io

# Install jenkins controller
  - name: Deploy jenkins chart with own values.yaml file
    become: false
    kubernetes.core.helm:
      name: jenkins
      chart_ref: jenkins/jenkins
      release_namespace: jenkins-system
      create_namespace: true
      values_files:
        - /vagrant/values.yaml

# kubectl set env daemonset/calico-node -n calico-system IP_AUTODETECTION_METHOD=interface=en.*
