---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-addresspool
  namespace: metallb-system
spec:
  addresses: 
  - 192.168.56.240-192.168.56.254 # range of IP adresses that will be assigned to the services
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-advertisement
  namespace: metallb-system