---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: test
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      run: test
  template:
    metadata:
      labels:
        run: test
    spec:
      containers:
      - image: docker-registry:5000/myubuntu:v1
        imagePullPolicy: Always
        name: test
      imagePullSecrets:
      - name: regsecret
