---
- hosts: all
  become: true
  tasks:
  
  - name: need to do this because kubeadm will fail otherwise
    shell: rm /etc/containerd/config.toml || true
    
  - name: need to do this because kubeadm will fail otherwise
    shell: containerd config default > /etc/containerd/config.toml # mkdir -p /etc/containerd

  - name: Restart containerd
    service:
      name: containerd
      daemon_reload: yes
      state: restarted
  
  - name: Initialize the Kubernetes cluster using kubeadm
    shell: kubeadm init --apiserver-advertise-address="192.168.56.10" --apiserver-cert-extra-sans="192.168.56.10"  --node-name master --pod-network-cidr=192.168.0.0/16

  - name: Setup kubeconfig for vagrant user
    shell: "{{ item }}"
    with_items:
      - mkdir -p /home/vagrant/.kube
      - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      - chown vagrant:vagrant /home/vagrant/.kube/config

#  - name: Install calico pod network
#    become: false
#    shell: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml

  - name: Generate join command
    shell: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      create: true
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

