---
- hosts: all
  become: true
  tasks:
  
  - name: need to do this because kubeadm will fail otherwise
    shell: rm /etc/containerd/config.toml || true
    
  - name: need to do this because kubeadm will fail otherwise
    shell: containerd config default > /etc/containerd/config.toml # mkdir -p /etc/containerd

  - name: Restart containerd
    service:
      name: containerd
      daemon_reload: yes
      state: restarted

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    shell: sh /tmp/join-command.sh

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      create: yes
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
